import os

DEBUG = True
USER_NAME = os.environ['USER_NAME']
PASSWORD_DATABASE = os.environ['PASSWORD_DATABASE']
HOST_DATABASE = os.environ['HOST_DATABASE']
DATA_BASE = os.environ['DATA_BASE']
DIALETO_DATABASE = os.environ['DIALETO_DATABASE']
DRIVER_DATABASE = os.environ['DRIVER_DATABASE']

SQLALCHEMY_DATABASE_URI = f'{DIALETO_DATABASE}+{DRIVER_DATABASE}://{USER_NAME}:{PASSWORD_DATABASE}@{HOST_DATABASE}/{DATA_BASE}?charset=utf8mb4'
SQLALCHEMY_TRACK_MODIFICATIONS = True
