"""empty message

Revision ID: 53529d9a4060
Revises: ff08ab753e44
Create Date: 2020-07-15 11:52:43.315464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53529d9a4060'
down_revision = 'ff08ab753e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto')
    # ### end Alembic commands ###
