"""empty message

Revision ID: ff08ab753e44
Revises: 3be2e396be1e
Create Date: 2020-07-11 17:20:49.178665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff08ab753e44'
down_revision = '3be2e396be1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefa', sa.Column('data_registro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefa', 'data_registro')
    # ### end Alembic commands ###
